---
title: "Elina P"
---

```{r}
library(tidyverse)
hltb <- read_csv("..//..//data//all-completions.csv")
games <- read_csv("..//..//data//games.csv")
metac <- read.csv("..//..//data//all_games.csv")
realgames <- games |>
  mutate(name = title) |>
  select(name, main_story, main_plus_extras, completionist, all_styles, type, platforms, genres)

palala <- metac |>
  left_join(realgames) |>
  mutate(gaga = release_date) |>
  separate(gaga, c("semester", "year"), "(?<=[,])") |>
  mutate(release_year = str_replace(year, " ", "")) |>
  mutate(user_review = as.integer(user_review)) |>
  mutate(release_year = as.integer(release_year)) |>
  select(-summary, -platform, -semester, -year) 

USETHISONE <- palala[!duplicated(USETHISONE$name), ] 
SPLITGENRES <- USETHISONE |>
  separate_rows(genres, sep = ", ") |>
  mutate(genres = str_to_upper(genres)) 

```

```{r}
USETHISONE |>
  group_by(release_year) |>
  mutate(meanmeta = mean(meta_score)) |>
  mutate(meanuser = mean(user_review)) |>
  ungroup() |>
  ggplot(aes(x = release_year, y = meanmeta)) +
  geom_point() + 
  labs(x = "Release Year", y = "Mean Metacritic Score") +
  geom_line() +
   theme(axis.text.x = element_text(size = 6))
  
```

```{r}
USETHISONE |>
  filter(main_story < 100) |>
  ggplot(aes(x = main_story, y = meta_score)) +
  geom_point(size = 0.6) 

USETHISONE |>
  ggplot(aes(x = main_story, y = user_review)) +
  geom_point() 

```

```{r}
USETHISONE |>
  ggplot(aes(x = user_review)) +
  geom_bar() +
  labs(x = "User Score", y = "Count") +
  scale_x_continuous(breaks=c(0,1,2,3,4,5,6,7,8,9))

USETHISONE |>
  ggplot(aes(x = meta_score)) +
  geom_histogram(color = "white", binwidth = 3) +
  labs(x = "Critic Score", y = "Count")


```
```{r}
USETHISONE |>
  filter(release_year == 2006) |>
  ggplot(aes(x = main_story, y = meta_score)) +
  geom_point()

USETHISONE |>
  filter(release_year == 2018) |>
  ggplot(aes(x = main_story, y = meta_score)) +
  geom_point()
```

```{r}
USETHISONE %>% drop_na(main_story)|>
  filter(release_year > 1999 ) |>
  filter(release_year < 2019) |>
  group_by(release_year) |>
  mutate(meanhltb = mean(main_story)) |>
  ungroup() |>
  ggplot(aes(x = release_year, y = meanhltb)) +
  geom_point()
  
```

