---
title: "Case Study"
---
The case study we examined was [the FiveThirtyEight analysis of fortune cookies.](https://fivethirtyeight.com/videos/fortune-cookie-math/)
The article actually addressed 4 different research questions: the number of unique fortunes in the set, how the "lucky numbers" compared to Powerball numbers (rated by expected winnings), the amount and character of Mandarin vocabulary that can be learned from the cookies, and the frequency of different types of messages.
The first thing that struck me was a very humorous and engaging tone throughout the article: this is particularly important because much of the data was not the kind of thing that could be communicated easily or most effectively through visualization. In fact, there are only two visualizations in the whole article: one that shows expected profits of playing the Powerball with the fortune cookie "lucky numbers" versus with random numbers, and a vertical bar graph that showed the relative frequencies of the different fortune subjects. For other data, like the character of the vocabulary, the author instead use word painting, comparisons (such as a 2-year olds vocabulary, or the first few lessons of a language course), and examples ("you could order that food cheap, delicious or even blue"), along with simply stating statistics, like the 124 nouns. Again, the craft was a big part of making this effective or memorable: a line like, "an adept student could eat, find a doctor and roller-skate" is unforgettable and illustrates the general bent of the data very well.
The one issue I found is that, being caught up in the fun aspects of the data led to oversights in regards to talking about limitations. Particularly, in evaluating the subject of the fortunes, the author mentions that over half the cookies mention the word "You". However, the earlier mention of these cookies being exclusively the run of fortunes that started with letters "A" to "I" or letters "W" to "Y" is not used to contextualize this data, which I would regard as egregious, because I imagine many of the "You" fortunes started with "You", all of which would be included in the "Y" run. This skew to the data is essentially completely brushed under the rug, which, while low-stakes, in ultimately not a very ethical data practice.

Regardless, among data analysis articles I have read, it is very engaging. Tone goes a long way to make data not just interesting, but meaningful, even memorable. It's made me consider "appeal" as another part of effective visualization
